<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;

class GeneralSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $settings = [
            [
                'setting_type'  => 1,
                'setting_name'  => 'favicon',
                'filed_label'   => 'Favicon (25*25)',
                'filed_type'    => 'file',
                'filed_value'   => 'application/favicon.png',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 1,
                'setting_name'  => 'logo',
                'filed_label'   => 'Logo',
                'filed_type'    => 'file',
                'filed_value'   => 'application/logo.png',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 1,
                'setting_name'  => 'application_name',
                'filed_label'   => 'Application Name',
                'filed_type'    => 'text',
                'filed_value'   => 'NSDL',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 1,
                'setting_name'  => 'copyright',
                'filed_label'   => 'Copyright',
                'filed_type'    => 'text',
                'filed_value'   => 'Copyright © 2021. All rights reserved.',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 1,
                'setting_name'  => 'address',
                'filed_label'   => 'Address',
                'filed_type'    => 'text',
                'filed_value'   => 'Paota, Jodhpur, Rajasthan - 342001',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 1,
                'setting_name'  => 'email',
                'filed_label'   => 'Email',
                'filed_type'    => 'text',
                'filed_value'   => 'lakshminarayan@adiyogitechnosoft.com',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 1,
                'setting_name'  => 'phone',
                'filed_label'   => 'Phone',
                'filed_type'    => 'text',
                'filed_value'   => '+91-7568457070',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 1,
                'setting_name'  => 'helpline_numbers',
                'filed_label'   => 'Helpline Numbers',
                'filed_type'    => 'text',
                'filed_value'   => '+91 0000000000, +91 0000000001',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 1,
                'setting_name'  => 'helpline_numbers_accounting',
                'filed_label'   => 'Helpline Numbers Accounting',
                'filed_type'    => 'text',
                'filed_value'   => '+91 0000000000',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 1,
                'setting_name'  => 'tagline',
                'filed_label'   => 'Tagline',
                'filed_type'    => 'text',
                'filed_value'   => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit accusamus quia recusandae nostrum porro non atque, dolores nobis blanditiis ea.',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 1,
                'setting_name'  => 'message_ticker',
                'filed_label'   => 'Message Ticker',
                'filed_type'    => 'textarea',
                'filed_value'   => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non repellendus ipsam eligendi ab quia quae rerum accusamus assumenda soluta ratione, iure rem? Facere, earum nobis.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non repellendus ipsam eligendi ab quia quae rerum accusamus assumenda soluta ratione, iure rem? Facere, earum nobis.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non repellendus ipsam eligendi ab quia quae rerum accusamus assumenda soluta ratione, iure rem? Facere, earum nobis.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non repellendus ipsam eligendi ab quia quae rerum accusamus assumenda soluta ratione, iure rem? Facere, earum nobis.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non repellendus ipsam eligendi ab quia quae rerum accusamus assumenda soluta ratione, iure rem? Facere, earum nobis.</p>',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 2,
                'setting_name'  => 'facebook',
                'filed_label'   => 'Facebook',
                'filed_type'    => 'text',
                'filed_value'   => 'https://www.facebook.com',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 2,
                'setting_name'  => 'twitter',
                'filed_label'   => 'Twitter',
                'filed_type'    => 'text',
                'filed_value'   => 'https://www.twitter.com',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 2,
                'setting_name'  => 'linkdin',
                'filed_label'   => 'Linkdin',
                'filed_type'    => 'text',
                'filed_value'   => 'https://www.linkdin.com',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 2,
                'setting_name'  => 'instagram',
                'filed_label'   => 'Instagram',
                'filed_type'    => 'text',
                'filed_value'   => 'https://www.instagram.com',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 3,
                'setting_name'  => 'email_from',
                'filed_label'   => 'Email From',
                'filed_type'    => 'text',
                'filed_value'   => 'info@test.com',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 3,
                'setting_name'  => 'smtp_host',
                'filed_label'   => 'SMTP Host',
                'filed_type'    => 'text',
                'filed_value'   => 'smtp.mailtrap.io',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 3,
                'setting_name'  => 'smtp_port',
                'filed_label'   => 'SMTP Port',
                'filed_type'    => 'text',
                'filed_value'   => '2525',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 3,
                'setting_name'  => 'smtp_user',
                'filed_label'   => 'SMTP User',
                'filed_type'    => 'text',
                'filed_value'   => '536193aec7fbd3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 3,
                'setting_name'  => 'smtp_pass',
                'filed_label'   => 'SMTP Password',
                'filed_type'    => 'text',
                'filed_value'   => 'aa67e007b19c27',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  4,
                'setting_name'  => 'is_commision',
                'filed_label'   => 'Is With Commision',
                'filed_type'    => 'check',
                'filed_value'   => '1',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  4,
                'setting_name'  => 'razorpay_key',
                'filed_label'   => 'Razor Key',
                'filed_type'    => 'text',
                'filed_value'   => 'rzp_test_pgT6USKA3JEYm2',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  4,
                'setting_name'  => 'razorpay_secret',
                'filed_label'   => 'Razor Secret',
                'filed_type'    => 'text',
                'filed_value'   => 'Y7WjHiX18Qqbi8fRes3K5G2l',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  4,
                'setting_name'  => 'merchant_id',
                'filed_label'   => 'Razor Merchant Id',
                'filed_type'    => 'text',
                'filed_value'   => 'Nothing',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  5,
                'setting_name'  => 'textlocal_key',
                'filed_label'   => 'TextLocal Key',
                'filed_type'    => 'text',
                'filed_value'   => 'ef01a009ac924d0d90c32a52d307b41e',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  5,
                'setting_name'  => 'textlocal_url',
                'filed_label'   => 'TextLocal URL',
                'filed_type'    => 'text',
                'filed_value'   => 'https://api.textlocal.in/send',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  5,
                'setting_name'  => 'textlocal_hash',
                'filed_label'   => 'TextLocal Hash',
                'filed_type'    => 'text',
                'filed_value'   => '1fb22d16eb8a4249a917856abaa2a9e9',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  5,
                'setting_name'  => 'textlocal_sender',
                'filed_label'   => 'TextLocal Sender Id',
                'filed_type'    => 'text',
                'filed_value'   => 'TXTLCL',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  6,
                'setting_name'  => 'notify_modal_show',
                'filed_label'   => 'Notify Modal Show',
                'filed_type'    => 'check',
                'filed_value'   => '1',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  6,
                'setting_name'  => 'notify_modal_content',
                'filed_label'   => 'Notify Modal Content',
                'filed_type'    => 'textarea-html',
                'filed_value'   => '<div>
                    <h5 class="text-danger text-center"> Dear PAAM / Login Manager User </h5>
                    <hr class="my-2">
                    <p class="text-center">
                        Our Banking Partner Server is Down for UPI Bank transfer Mode
                        due to some technical glitch at their end. We apologies for
                        Inconvenience. Kindly process the payment through
                    </p>
                    <h6 class="text-success text-center">Your UPI code (ALTRUIc9875@yesbankltd)</h6>
                    <p class="text-center mb-1 fw-bold ">except from UPI Bank transfer Mode.</p>
                    <p class="text-center mb-1">for paperless recharge use QR Code </p>
                    <p class="text-center mb-1">Thank you</p>
                </div>',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  =>  6,
                'setting_name'  => 'load_money_qr_code',
                'filed_label'   => 'Load Money QR Code',
                'filed_type'    => 'file',
                'filed_value'   => 'images/qr-code.jpeg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'force_update_android',
                'filed_label'   => 'Force Update Android',
                'filed_type'    => 'check',
                'filed_value'   => '1',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'force_update_ios',
                'filed_label'   => 'Force Update IOS',
                'filed_type'    => 'check',
                'filed_value'   => '1',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'app_version_android',
                'filed_label'   => 'App Version Android App',
                'filed_type'    => 'number',
                'filed_value'   => '1.0',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'app_version_ios',
                'filed_label'   => 'App Version IOS App',
                'filed_type'    => 'number',
                'filed_value'   => '1.0',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],

            [
                'setting_type'  => 7,
                'setting_name'  => 'app_url_android',
                'filed_label'   => 'App URL Android App',
                'filed_type'    => 'text',
                'filed_value'   => 'https://play.google.com/store',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'app_url_ios',
                'filed_label'   => 'App URL IOS App',
                'filed_type'    => 'text',
                'filed_value'   => 'https://www.apple.com/in/app-store',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'force_update_message_android',
                'filed_label'   => 'Force Update Message Android',
                'filed_type'    => 'textarea',
                'filed_value'   => 'Force Update Message..',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'force_update_message_ios',
                'filed_label'   => 'Force Update Message IOS',
                'filed_type'    => 'textarea',
                'filed_value'   => 'Force Update Message..',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'maintenance',
                'filed_label'   => 'Maintenance',
                'filed_type'    => 'textarea',
                'filed_value'   => 'Under Maintenance',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'maintenance_toggle',
                'filed_label'   => 'Maintenance Toggle',
                'filed_type'    => 'check',
                'filed_value'   => '1',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'information_banner',
                'filed_label'   => 'Information Banner',
                'filed_type'    => 'file',
                'filed_value'   => '',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'setting_type'  => 7,
                'setting_name'  => 'information_banner_toggle',
                'filed_label'   => 'Information Banner Toggle',
                'filed_type'    => 'check',
                'filed_value'   => '0',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
        ];

        Setting::truncate();
        Setting::insert($settings);
    }
}
